//! Vendored dioxus-primitives styled components (added via `dx components add`).
//! These are adopted incrementally, so some may be unused between migration phases.
#![allow(dead_code, unused_imports)]

// AUTOGENERATED Components module
pub mod button;
pub mod dialog;
pub mod select;
pub mod slider;
